config/routes.rb
Ticketee::Application.routes.draw do

  devise_for :users, :controllers => { :registrations => "registrations" }
  
  get '/awaiting_confirmation',
    :to => "users#confirmation",
    :as => 'confirm_user'
    
  put '/admin/users/:user_id/permissions',
    :to => 'admin/permissions#update',
    :as => :update_user_permissions

  resources :projects do
    resources :tickets
  end
  
  resources :tickets do
    resources :comments
    resources :tags do
      member do
        delete :remove
      end
    end
  end
  
  root :to => "projects#index"
  
  namespace :admin do
    root :to => "base#index"
    resources :states do
      member do
        get :make_default
      end
    end
    resources :users do
      resources :permissions
    end
  end
  
  resources :files
  

end

app/models/project.rb
class Project < ActiveRecord::Base
  has_many :tickets, :dependent => :delete_all
  validates :name, :presence => true, :uniqueness => true
  
  has_many :permissions, :as => :thing
  scope :readable_by, lambda { |user| 
    joins(:permissions).where(:permissions => { :action => "view", :user_id => user.id })
    }
    
  def self.for(user)
    user.admin? ? Project : Project.readable_by(user)
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  
  before_filter :authorize_admin!, :except => [:index, :show]
  before_filter :authenticate_user!, :only => [:index, :show]
  before_filter :find_project, :only => [:show, :edit, :update, :destroy]
  
  def index
    @projects = Project.for(current_user).all
  end
  
  def new
    @project = Project.new
  end
  
  def create
    @project = Project.new(params[:project])
    if @project.save
      flash[:notice] = "Project has been created."
      redirect_to @project
    else
      flash[:alert] = "Project has not been created."
      render :action => "new"
    end
  end
  
  def show
    
  end
  
  def edit
    
  end
  
  def update
    if @project.update_attributes(params[:project])
      flash[:notice] = "Project has been updated."
      redirect_to @project
    else
      flash[:alert] = "Project has not been updated."
      render :action => "edit"
    end
  end
  
  def destroy
    @project.destroy
    flash[:notice] = "Project has been deleted."
    redirect_to projects_path
  end
  
  private
    def find_project
      @project = Project.for(current_user).find(params[:id])
      rescue ActiveRecord::RecordNotFound
      flash[:alert] = "The project you were looking for could not be found."
      redirect_to projects_path
    end
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_form.html.erb
<%= form_for @project, :html => {:class => "form-horizontal"} do |f| %>
  <%= f.error_messages %>

  <div class="control-group">
    <%= f.label :name, :class => "control-label" %>
    <div class="controls">
      <%= f.text_field :name, :class => "input-xlarge" %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.submit :class => "btn btn-primary" %>
  </div>
<% end %>

app/views/projects/edit.html.erb
<% title("Edit Project") %>
<% header_title("Edit Project") %>

<% content_for :functionality do %>
  <%= back_button(@project.name, project_path(@project)) %>
<% end %>

<%= render "form" %>

app/views/projects/index.html.erb
<% title("Projects") %>
<% header_title("Projects") %>
<% content_for :functionality do %>
  <%= admins_only do %>
    <%= link_to "New Project", new_project_path, :class => 'btn btn-success' %>
  <% end %>
<% end %>

<% if @projects.empty? %>
  <div class='alert'>
    There are no projects. Click <%= link_to "here", new_project_path %> to create one.
  </div>
<% else %>
  <ul class='nav nav-pills nav-stacked' id='projects'>
    <% for project in @projects %>
      <li class='project-pill'>
        <%= link_to project.name, project %>
      </li>
    <% end %>
  </ul>
<% end %>

app/views/projects/new.html.erb
<% title("New Project") %>
<% header_title("New Project") %>

<% content_for :functionality do %>
  <%= back_button("projects", projects_path) %>
<% end %>

<%= render "form" %>

app/views/projects/show.html.erb
<% title(@project.name, "Projects") %>
<% header_title(@project.name) %>

<% content_for :functionality do %>
  <%= authorized?("create tickets".to_sym, @project) do %>
    <%= link_to "New Ticket", new_project_ticket_path(@project), :class => 'btn btn-success' %>
  <% end %>
  <%= admins_only do %>
    <%= link_to "Edit Project", edit_project_path(@project), :class => 'btn btn-warning' %>
    <%= link_to "Delete Project", @project, :method => :delete, :confirm => "Are you sure you want to delete this project?", :class => 'btn btn-danger' %>
  <% end %>
  <%= back_button("projects", projects_path) %>
<% end %>

<% if @project.tickets.empty? %>
  <div class='alert'>
    There are no tickets.
    <%= authorized?("create tickets".to_sym, @project) do %>
      Click <%= link_to 'here', new_project_ticket_path(@project) %> to create one.
   <% end %>
  </div>
<% else %>
  <ul class='nav nav-pills nav-stacked' id='tickets'>
    <% @project.tickets.each do |ticket| %>
      <li>
        <%= render ticket.state if ticket.state %>
        #<%= ticket.id %> - <%= link_to ticket.title, [@project, ticket] %>
      </li>
    <% end %>
  </ul>
<% end %>