config/routes.rb
Ticketee::Application.routes.draw do

  devise_for :users, :controllers => { :registrations => "registrations" }
  
  get '/awaiting_confirmation',
    :to => "users#confirmation",
    :as => 'confirm_user'
    
  put '/admin/users/:user_id/permissions',
    :to => 'admin/permissions#update',
    :as => :update_user_permissions

  resources :projects do
    resources :tickets
  end
  
  resources :tickets do
    resources :comments
    resources :tags do
      member do
        delete :remove
      end
    end
  end
  
  root :to => "projects#index"
  
  namespace :admin do
    root :to => "base#index"
    resources :states do
      member do
        get :make_default
      end
    end
    resources :users do
      resources :permissions
    end
  end
  
  resources :files
  

end

app/models/state.rb
class State < ActiveRecord::Base
  
  def to_s
    name
  end
  
  def default!
    current_default_state = State.find_by_default(true)
    
    self.default = true
    self.save!
    
    if current_default_state
      current_default_state.default = false
      current_default_state.save!
    end
  end
  
end

app/controllers/admin/states_controller.rb
class Admin::StatesController < Admin::BaseController
  
  def index
    @states = State.all
  end
  
  def new
    @state = State.new
  end
  
  def create
    @state = State.new(params[:state])
    if @state.save
      flash[:notice] = "State has been created."
      redirect_to admin_states_path
    else
      flash[:alert] = "State has not been created."
      render :action => "new"
    end
  end
  
  def make_default
    @state = State.find(params[:id])
    @state.default!
    
    flash[:notice] = "#{@state.name} is now the default state."
    redirect_to admin_states_path
  end
end

app/helpers/admin/states_helper.rb
module Admin::StatesHelper
end

app/views/admin/states/_form.html.erb
<%= form_for [:admin, @state], :html => {:class => "form-horizontal"} do |f| %>
  <%= f.error_messages %>

  <div class="control-group">
    <%= f.label :name, :class => "control-label" %>
    <div class="controls">
      <%= f.text_field :name, :class => "input-xlarge" %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.submit :class => "btn btn-primary" %>
  </div>
<% end %>

app/views/admin/states/index.html.erb
<% title("States", "Admin Lounge") %>
<% header_title("States") %>

<% content_for :functionality do %>
  <%= link_to "New State", new_admin_state_path, :class => 'btn btn-success' %>
  <%= back_button("Admin Lounge", admin_root_path) %>
<% end %>

<ul class='nav nav-pills nav-stacked' id='states'>
  <% for state in @states %>
    <li id='state_<%= state.id %>' class='state-pill'>
      <p>
        <%= state.name %>
      </p>
      <%= link_to "Make default", make_default_admin_state_path(state) %>
    </li>
  <% end %>
</ul>

app/views/admin/states/new.html.erb
<% title("New State", "Admin Lounge") %>
<% header_title("New State") %>

<% content_for :functionality do %>
  <%= back_button("states", admin_states_path) %>
<% end %>

<%= render "form" %>